### ISSUE TITLE
혹시 리눅스도 구성방법알려줄수있니

### ISSUE THREAD

**Issue by jkh702** [juunini/palworld-discord-bot#17]
혼자시도해보다 대가리깨져서 실패했음 구글클라우드 서버굴리고있는데 리눅스파일받아서 서버에서 뭘해야될지 감도안잡힌다

**Comment by juunini** [comment]
음.... 일단 본문 들어가기 전에, 디씨에서는 용인되는 반말 어체가 밖에서는 사용하면 안된다는걸 짚고 시작해야 할 것 같습니다.

해결 방법은 쉽게 볼 때  
두 가지가 있을 것 같습니다.

1. 한번 실행한 뒤 종료하면 .env 파일이 생성되는데,  
    vim이나 nano같은 에디터를 사용해서 직접 수정하는 방법  
    (설명은 설정하는 라인마다 윗줄에 적혀있습니다)
2. 웹 인터페이스 쓰고싶다면, 잠깐 사용하려는 시간동안만 60000번 포트를 열고,  
    http://<서버IP>:60000 으로 들어가서 설정을 한 뒤,  
    설정을 끝마친 뒤 닫기

위 두 가지가 가장 쉬운 방법일듯 합니다.

**Comment by juunini** [comment]
아마 이렇게 알려드려도 리눅스와 서버에 대한 지식이 없다면  
둘 다 어려운 방식일 것으로 생각 되기도 합니다.

가까운 시일 내에 이 방법들도 가이드를 작성해서 올리거나 해야겠군요.  
좋은 질문 감사드립니다.

**Comment by jkh702** [comment]
아 그대로넘어와서 생각없이 말했네요 죄송합니다 일단 알려주신대로 최대한 도전해보다 도저히안되겠으면 가이드를 기다려볼게요

**Comment by juunini** [comment]
https://github.com/juunini/palworld-discord-bot/wiki/%5BGoogle-Cloud%5D-How-to-open-Web-UI-Port%3F-%5B%ED%95%9C%EA%B5%AD%EC%96%B4%5D

여길 참고하세요.  
이슈는 닫아두겠습니다.  

혹시 그래도 모르겠거든 다시 이슈를 열고 질문 주세요.
