### ISSUE TITLE
안녕하세요 마이너에서 보고 생각보다 편하게 셋팅했습니다.

### ISSUE THREAD

**Issue by ravensthis** [juunini/palworld-discord-bot#18]
팰월드 때문에 우분투 공부하면서 친구들과 서버를 꾸려 하나씩 이것 저것 해보고 있습니다.

정리도 너무 잘해주시고 못쓰고 있던 RCON까지 활용하게 되었습니다 !

무한한 감사를 드립니다.

제가 지금 서버를 다른 곳에 우분투를 두고 집에서 Putty를 이용하거나 집에서 MSTSC(터미널)를 이용해서 작업중인데 제가 잘못해서 Putty와 MSTSC(터미널)중복 실행을 해버리고 나니 웹페이지에서 수정을 해도 .env파일이 수정되지 않았습니다. 제가 잘 몰라서 그런건지 모르겠지만 .env파일을 아예 삭제해서 새로 셋팅하니 멀쩡해졌습니다 ! 원래 이런거면 별문제 없이 기쁘게 쓸 것 같습니다 ㅎㅎ

개발 노고에 대해 너무 감사드립니다.

항상 건강하세요~

**Comment by juunini** [comment]
아.. 여러곳에서 .env 파일을 vim이나 nano같은 에디터로 실행을 한 상태면  
양쪽에서 파일을 stream 하고 있는 상태이기 때문에  
수정이 불가능한 상황이었을겁니다.

아마 삭제를 한 순간에 stream 상태가 깨졌을거고  
그리고 새로 만든 .env 파일이 수정이 가능한 상태가 되었을겁니다.

**Comment by ravensthis** [comment]
무지가 낳은 에피소드였네요 ㅋㅋ
친구들도 다들 편하다고 좋아 죽을려고 그러네요.
자주 확인하면서 업데이트 있으면 또 와서 열심히 해보도록 하겠습니다.
너무 감사합니다. 추운데 건강 조심하세요

**Comment by juunini** [comment]
감사합니다. 그럼 이슈는 닫아두도록 하겠습니다.
꾸준히 업뎃 해서 편의기능을 더 추가하도록 하겠습니다
