### ISSUE TITLE
에러 문의

### ISSUE THREAD

**Issue by SunjaeJang** [juunini/palworld-discord-bot#22]
디코봇 쓰려고 설정 중인데요

일단 서버는 서버용 PC에 WindowsGSM 사용해서 만들었습니다.
만들어주신 디코봇 깔고 설정 하고 실행하면 아래와 같이 메세지 나옵니다.

[1;31mRCON 서버에 연결하는데 실패했습니다.: Error connecting to 182.228.233.87:25575 - dial tcp 182.228.233.87:25575: i/o timeout[0m
[1;31mRCON 서버에 연결하는데 실패했습니다.[0m

디코에 일단 디코봇 입장까진 됐고, 도움말 출력은 되는데 서버 시작이나 등등 명령어 넣으면 "RCON 서버에 연결하는데 실패했습니다. "라는 메세지 나오고 안됩니다.

세팅 파일에서 Rcon True로 바꿔 줬고, 디코봇 설정에서 Rcon host에 제 공인 IP, 내부망 ip, 127.0.0.1 셋다 넣어도 똑같습니다. 
포트포워딩으로 25575 TCP,UDP 둘다 열어 줬습니다.

왜 그럴까요

**Comment by SunjaeJang** [comment]
전부 다 삭제하고 다시 설치하고 봇 다시 만들어서 했는데 이번에는 Rcon 에러 메세지는 안나오지만 디스코드에서 명령어를 넣었을 경우 서버시작만 동작하고 나머지 명령어들은 전부 "RCON 서버에 연결하는데 실패했습니다." 라는 메세지가 나옵니다. 

IP를 공인IP, 내부망, 127.0.0.1 셋다 바꿔 봐도 동일 합니다. 

![디코 화면](https://github.com/juunini/palworld-discord-bot/assets/102493552/c73ede58-5e98-47ee-95f8-e5553ef78204)
![디코봇셋팅](https://github.com/juunini/palworld-discord-bot/assets/102493552/a06d027b-6989-479b-8a28-ba588800505c)
![셋팅파일](https://github.com/juunini/palworld-discord-bot/assets/102493552/c73ca493-b403-4c39-83cf-0c26cf36b96e)

**Comment by juunini** [comment]
팰월드 서버를 올린 서버에 디코봇을 같이 돌려야 모든 기능을 사용할 수 있습니다.
그런 경우엔 RCON Host는 127.0.0.1로 둬야 하고

v0.1.5.0 에서 RCON 서버가 안열리는 이슈가 있는데
지금 어떤 버전으로 돌리고 계신가요?

PalWorldSettings.ini 파일을 변경하면 서버를 재시작 해야 적용이 됩니다.

**Comment by SunjaeJang** [comment]
서버를 올린 서버에 디코봇을 같이 돌린다는게 어떤 의미 인가요??
일단 서버 설치된 곳에 디코봇 실행 파일은 같은 폴더 안에 들어 있습니다. 

버전은 V0.1.5.1 입니다. 

셋팅 파일에서 Rcon True로 변경하고 재시작 했었습니다.

**Comment by SunjaeJang** [comment]
와 해결 했습니다. 제가 거점 20마리 늘리게 해주는 거 사용중이었는데 그거 없애고 
일단 먼저 셋팅 하고 다시 설치 하니깐 되네요.

그게 월드 옵션 파일을 따로 생성해주는 프로그램인데 기존에 config에 있는 월드 셋팅파일 수정이 안먹힌다고 했거든요 

그거 갑자기 생각나서 지우고 먼저 셋팅 바꾼다음에 디코봇 설치 하고 
월드 셋팅 변경 프로그램 까니깐 디코봇 작동하네요.

감사합니다. 

아 그리고 서버 저장이라는게 혹시 백업 파일 만들어 주는건가요??
지금 데디서버 인데 저번에 갑자기 컴터 꺼지고 나서 초기화 되서 saved 폴더 밑에 파일 따로 백업 해둬야 한다고 들었는데 그 파일을 저장 해주는 기능인가요?

**Comment by juunini** [comment]
해결 하셔서 다행이네요 ㅎㅎ

따로 백업해주는 기능은 아니고
팰월드 내에 Admin 커맨드 중에
`/Save` 라는 커맨드 써주는겁니다.

저도 그거 쓰면 어떻게 되는지는 모르겠네요...ㅠㅠ

`saved` 폴더 밑에 따로 백업하는 하드백업 기능은 다음번에 추가해봐야겠습니다.
아마 하드백업 하려면 팰월드 서버를 끄고 진행해야 될겁니다.

좋은 의견 감사합니다.
해결됐으니 이슈는 닫아두겠습니다.

**Comment by SunjaeJang** [comment]
넵 감사합니다  서버 파일 백업은 다른 글 보고 해보려고 합니다 나중에 기능 추가 하실때 참고 하시라고 제가 보는곳 남겨 두겠습니다.

https://arca.live/b/palworld/97387921
